/*!
 * @file aarch64.h
 * @brief Macros for ARM v8.5 memory tagging.
 */

/*!
 * @brief Tags to be randomly generated by hardware, default is 15 tags
 */
#define PLATFORM_AARCH64_TAGS 0xfffe

/*!
 * @brief Tags the pointer with random tag.
 */
#define insert_random_tag(ptr)                  \
  ({                                            \
    uint64_t __val;                             \
    asm("irg %0, %1" : "=r"(__val) : "r"(ptr)); \
    __val;                                      \
  })

/*!
 * @brief Tags the memory granule (16-byte) with same tag as the tagged_addr.
 */
#define set_tag(tagged_addr)                                      \
  do {                                                            \
    asm volatile("stg %0, [%0]" : : "r"(tagged_addr) : "memory"); \
  } while (0)
