/*!
 * @file aarch64.h
 * @brief Macros for ARM v8.5 memory tagging.
 */

#include <stdint.h>

/*!
 * @brief Tags to be randomly generated by hardware, default is 15 tags
 */
#define PLATFORM_AARCH64_TAGS 0xfffe

#define TAG_OFFSET_BITS 56

/*!
 * @brief Size of memory granule
 */
#define MEMORY_GRANULE_SIZE 16
#define MEMORY_2_GRANULE_SIZE 32

